var jsonWeaponTypeList = {
    "Unarmed": "Unarmed",
    "Dagger": "Dagger",
    "1hSword": "One-handed Sword",
    "2hSword": "Two-handed Sword",
    "1hSpear": "One-handed Spear",
    "2hSpear": "Two-handed Spear",
    "1hAxe": "One-handed Axe",
    "2hAxe": "Two-handed Axe",
    "Mace": "Mace",
    "2hMace": "2hMace(unused)",
    "Staff": "Staff",
    "Bow": "Bow",
    "Knuckle": "Knuckle",
    "Musical": "Instrument",
    "Whip": "Whip",
    "Book": "Book",
    "Katar": "Katar",
    "Revolver": "Revolver",
    "Rifle": "Rifle",
    "Gatling": "Gatling Gun",
    "Shotgun": "Shotgun",
    "Grenade": "Grenade Launcher",
    "Huuma": "Huuma Shuriken",
    "2hStaff": "Two-handed Staff",
    "Shield": "Shield"
};

var jsonClassList = {
    " 0": "Novice",
    " 1": "Swordman",
    " 2": "Mage",
    " 3": "Archer",
    " 4": "Acolyte",
    " 5": "Merchant",
    " 6": "Thief",
    " -1": "─────────────────",
    " 7": "Knight",
    " 8": "Priest",
    " 9": "Wizard",
    " 10": "Blacksmith",
    " 11": "Hunter",
    " 12": "Assassin",
    " 14": "Crusader",
    " 15": "Monk",
    " 16": "Sage",
    " 17": "Rogue",
    " 18": "Alchemist",
    " 19": "Bard",
    " 20": "Dancer",
    " -2": "─────────────────",
    " 4001": "Novice High",
    " 4002": "Swordman High",
    " 4003": "Magician High",
    " 4004": "Archer High",
    " 4005": "Acolyte High",
    " 4006": "Merchant High",
    " 4007": "Thief High",
    " -3": "─────────────────",
    " 4008": "Lord Knight",
    " 4009": "High Priest",
    " 4010": "High Wizard",
    " 4011": "Whitesmith",
    " 4012": "Sniper",
    " 4013": "Assassin Cross",
    " 4015": "Paladin",
    " 4016": "Champion",
    " 4017": "Professor",
    " 4018": "Stalker",
    " 4019": "Creator",
    " 4020": "Clown",
    " 4021": "Gypsy",
    " -4": "─────────────────",
    " 4060": "Rune Knight (trans)",
    " 4061": "Warlock (trans)",
    " 4062": "Ranger (trans)",
    " 4063": "Arch Bishop (trans)",
    " 4064": "Mechanic (trans)",
    " 4065": "Guillotine Cross (trans)",
    " 4073": "Royal Guard (trans)",
    " 4074": "Sorcerer (trans)",
    " 4075": "Minstrel (trans)",
    " 4076": "Wanderer (trans)",
    " 4077": "Sura (trans)",
    " 4078": "Genetic (trans)",
    " 4079": "Shadow Chaser (trans)",
    " -5": "─────────────────",
    " 4054": "Rune Knight (non-trans)",
    " 4055": "Warlock (non-trans)",
    " 4056": "Ranger (non-trans)",
    " 4057": "Arch Bishop (non-trans)",
    " 4058": "Mechanic (non-trans)",
    " 4059": "Guillotine Cross (non-trans)",
    " 4066": "Royal Guard (non-trans)",
    " 4067": "Sorcerer (non-trans)",
    " 4068": "Minstrel (non-trans)",
    " 4069": "Wanderer (non-trans)",
    " 4070": "Sura (non-trans)",
    " 4071": "Genetic (non-trans)",
    " 4072": "Shadow Chaser (non-trans)",
    " -6": "─────────────────",
    " 23": "Super Novice",
    " 24": "Gunslinger",
    " 25": "Ninja",
    " 4046": "Taekwon",
    " -7": "─────────────────",
    " 4047": "Star Gladiator",
    " 4049": "Soul Linker",
    " 4211": "Kagerou",
    " 4212": "Oboro",
    " 4215": "Rebellion",
    " 114": "Expanded Super Novice",
    " -8": "─────────────────",
    " 4239": "Star Emperor",
    " 4240": "Soul Reaper",
    " -9": "─────────────────",
    " 4218": "Summoner"
}

var jsonPrimaryStatList = {
    "0": "Str",
    "1": "Agi",
    "2": "Vit",
    "3": "Int",
    "4": "Dex",
    "5": "Luk",
}

var jsonSubStatList = {
    "0": "Atk_status",
    "1": "Atk_weapon",
    "2": "Matk_status",
    "3": "Matk_weapon",
    "4": "Def_soft",
    "5": "Def_hard",
    "6": "Mdef_soft",
    "7": "Mdef_hard",
    "8": "Hit",
    "9": "Critical",
    "10": "Flee",
    "11": "PerfectDodge",
    "12": "Aspd",
    "13": "HP",
    "14": "SP",
    "15": "WeightLimit",
    "16": "PendingStatPoints",
    "17": "AttackRange",
    "18": "CastTimeReduction_variable",
    "19": "CastTimeReduction_Fixed",
    "20": "PerfectHit",
    "21": "Movement Speed",
    "22": "StatusResistance"
}

var jsonEquipmentList = {
    "0": {
        "Name": "Head_Top",
        "Label": "Top Head",
        "CardSlots": 1,
        "refine": true
    },
    "1": {
        "Name": "Head_Mid",
        "Label": "Mid Head",
        "CardSlots": 1,
        "refine": false
    },
    "2": {
        "Name": "Head_Low",
        "Label": "Lower Head",
        "CardSlots": 1,
        "refine": false
    },
    "3": {
        "Name": "Armor",
        "Label": "Armor",
        "CardSlots": 1,
        "refine": true
    },
    "4": {
        "Name": "Right_Hand",
        "Label": "Right Hand",
        "CardSlots": 4,
        "refine": true
    },
    "5": {
        "Name": "Left_Hand",
        "Label": "Left Hand",
        "CardSlots": 4,
        "refine": true
    },
    "6": {
        "Name": "Garment",
        "Label": "Garment",
        "CardSlots": 1,
        "refine": true
    },
    "7": {
        "Name": "Shoes",
        "Label": "Shoes",
        "CardSlots": 1,
        "refine": true
    },
    "8": {
        "Name": "Right_Accessory",
        "Label": "Right Accessory",
        "CardSlots": 1,
        "refine": true
    },
    "9": {
        "Name": "Left_Accessory",
        "Label": "Left Accessory",
        "CardSlots": 1,
        "refine": true
    }
}